In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Prave\OneDrive\Documents\employees.csv")

df

     Name Department  Salary
0    Arun         IT   25000
1    Bala         HR   20000
2  Charan         IT   30000
3   Divya         HR   22000
4   Ezhil         IT   28000
5   Kavin         HR   24000

In [5]:
df.head(6)

     Name Department  Salary
0    Arun         IT   25000
1    Bala         HR   20000
2  Charan         IT   30000
3   Divya         HR   22000
4   Ezhil         IT   28000
5   Kavin         HR   24000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      6 non-null      int64
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [7]:
df.describe()

             Salary
count      6.000000
mean   24833.333333
std     3710.345896
min    20000.000000
25%    22500.000000
50%    24500.000000
75%    27250.000000
max    30000.000000

In [9]:
df["Name"]

0      Arun
1      Bala
2    Charan
3     Divya
4     Ezhil
5     Kavin
Name: Name, dtype: str

In [11]:
df[["Name","Salary"]]

     Name  Salary
0    Arun   25000
1    Bala   20000
2  Charan   30000
3   Divya   22000
4   Ezhil   28000
5   Kavin   24000

In [13]:
df[df["Department"]=="IT"]

     Name Department  Salary
0    Arun         IT   25000
2  Charan         IT   30000
4   Ezhil         IT   28000

In [14]:
df[df["Salary"]>25000]

     Name Department  Salary
2  Charan         IT   30000
4   Ezhil         IT   28000

In [17]:
df[(df["Department"]=="IT") & (df["Salary"]>25000)]

     Name Department  Salary
2  Charan         IT   30000
4   Ezhil         IT   28000

In [20]:
df.isna().sum()

Name          0
Department    0
Salary        0
dtype: int64

In [21]:
df_test = df.copy()

df_test.loc[1, "Salary"] = None

df_test.isna().sum()

Name          0
Department    0
Salary        1
dtype: int64

In [22]:
df_clean = df_test.dropna()

In [23]:
df_test["Salary"] = df_test["Salary"].fillna(
    df_test["Salary"].median()
)

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df_test2 = pd.concat([df, df.iloc[[0]]], ignore_index=True)

df_test2.duplicated().sum()

np.int64(1)

In [26]:
df_unique = df_test2.drop_duplicates()

df_unique

     Name Department  Salary
0    Arun         IT   25000
1    Bala         HR   20000
2  Charan         IT   30000
3   Divya         HR   22000
4   Ezhil         IT   28000
5   Kavin         HR   24000

In [27]:
df.groupby("Department")["Salary"].mean()

Department
HR    22000.000000
IT    27666.666667
Name: Salary, dtype: float64

In [28]:
df.groupby("Department")["Name"].count()

Department
HR    3
IT    3
Name: Name, dtype: int64

In [29]:
df.groupby("Department")["Salary"].sum()

Department
HR    66000
IT    83000
Name: Salary, dtype: int64

In [30]:
df.groupby("Department")["Salary"].agg(["min", "max", "mean"])

              min    max          mean
Department
HR          20000  24000  22000.000000
IT          25000  30000  27666.666667

In [31]:
df_clean = df.drop_duplicates().copy()

df_clean = df_clean.dropna()

df_clean

     Name Department  Salary
0    Arun         IT   25000
1    Bala         HR   20000
2  Charan         IT   30000
3   Divya         HR   22000
4   Ezhil         IT   28000
5   Kavin         HR   24000

In [32]:
df_clean.to_csv("employees_cleaned.csv", index=False)