In [1]:
import pandas as pd
print("Pandas version:", pd.__version__)
print("Week 2 Day 2 started!")

Pandas version: 3.0.1
Week 2 Day 2 started!

In [2]:
import pandas as pd
employees = pd.DataFrame({
    "employee_id": [101, 102, 103, 104],
    "name": ["Arun", "Bala", "Charan", "Divya"],
    "dept_id": [1, 2, 1, 3]
})
departments = pd.DataFrame({
    "dept_id": [1, 2, 3],
    "department": ["IT", "HR", "Finance"]
})
print("Employees Table:")
display(employees)
print("Departments Table:")
display(departments)

Employees Table:

   employee_id    name  dept_id
0          101    Arun        1
1          102    Bala        2
2          103  Charan        1
3          104   Divya        3

Departments Table:

   dept_id department
0        1         IT
1        2         HR
2        3    Finance

In [7]:
inner_join = pd.merge(
    employees,
    departments,
    on="dept_id",
    how="inner"
)
display(inner_join)

   employee_id    name  dept_id department
0          101    Arun        1         IT
1          102    Bala        2         HR
2          103  Charan        1         IT
3          104   Divya        3    Finance

In [8]:
left_join = pd.merge(
    employees,
    departments,
    on="dept_id",
    how="left"
)
display(left_join)

   employee_id    name  dept_id department
0          101    Arun        1         IT
1          102    Bala        2         HR
2          103  Charan        1         IT
3          104   Divya        3    Finance

In [9]:
right_join = pd.merge(
    employees,
    departments,
    on="dept_id",
    how="right"
)
display(right_join)

   employee_id    name  dept_id department
0          101    Arun        1         IT
1          103  Charan        1         IT
2          102    Bala        2         HR
3          104   Divya        3    Finance

In [10]:
outer_join = pd.merge(
    employees,
    departments,
    on="dept_id",
    how="outer"
)
display(outer_join)

   employee_id    name  dept_id department
0          101    Arun        1         IT
1          103  Charan        1         IT
2          102    Bala        2         HR
3          104   Divya        3    Finance

In [ ]:
sales = pd.DataFrame({
    "Region": ["South", "North", "South", "North", "South"],
    "Product": ["Laptop", "Laptop", "Phone", "Phone", "Laptop"],
    "Sales": [50000, 40000, 20000, 30000, 10000]
})
display(sales)

  Region Product  Sales
0  South  Laptop  50000
1  North  Laptop  40000
2  South   Phone  20000
3  North   Phone  30000
4  South  Laptop  10000

In [13]:
sales_summary = pd.pivot_table(
    sales,
    index="Region",
    columns="Product",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)
display(sales_summary)

Product  Laptop  Phone
Region
North     40000  30000
South     60000  20000

In [ ]:
salary = pd.DataFrame({
    "Employee": ["Arun", "Bala"],
    "January": [20000, 25000],
    "February": [22000, 26000],
    "March": [21000, 27000]
})
display(salary)

  Employee  January  February  March
0     Arun    20000     22000  21000
1     Bala    25000     26000  27000

In [15]:
long_data = pd.melt(
    salary,
    id_vars=["Employee"],
    var_name="Month",
    value_name="Salary"
)
display(long_data)

  Employee     Month  Salary
0     Arun   January   20000
1     Bala   January   25000
2     Arun  February   22000
3     Bala  February   26000
4     Arun     March   21000
5     Bala     March   27000

In [ ]:
sales_data = pd.DataFrame({
    "Region": ["South", "North", "South", "West", "North"],
    "Sales": [15000, 8000, 25000, None, 30000]
})
result = (
    sales_data
    .dropna(subset=["Sales"])
    .query("Sales > 10000")
    .groupby("Region", as_index=False)["Sales"]
    .sum()
    .sort_values("Sales", ascending=False)
)
display(result)

  Region    Sales
1  South  40000.0
0  North  30000.0